# export $(cat .env | xargs)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/micauth
    username: ulocal
    password: plocal
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:file:.env

