name: Snyk Security

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  security-events: write

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Dar permisos de ejecuci贸n al Maven Wrapper (mvnw)
      - name: Set Execution Permissions for Maven Wrapper (mvnw)
        run: if [ -f mvnw ]; then chmod +x mvnw; fi

      # Configuraci贸n del Entorno Java/Maven
      - name: Set up Java for Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Pre-construcci贸n de Dependencias
      - name: Pre-build Maven Dependencies (Troubleshooting)
        run: mvn dependency:tree -DoutputType=dot --batch-mode

      #  PASO 1: Configurar Snyk CLI
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb

      #  PASO 2: Autenticaci贸n Expl铆cita
      # Esto fuerza a la CLI a usar el token antes de escanear.
      - name: Snyk Explicit Authentication
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # 1. Snyk Code
      - name: Snyk Code test and generate SARIF
        run: snyk code test --sarif > snyk-code.sarif
        continue-on-error: true

      # 2. Snyk Open Source (Monitorea dependencias)
      - name: Snyk Open Source monitor
        run: snyk monitor --all-projects
        working-directory: ./

      # 3. Snyk IaC
      - name: Snyk IaC test and report
        run: snyk iac test --report
        continue-on-error: true
        working-directory: ./

      # 4. Snyk Container (Descomentado cuando sea necesario)
      # - name: Build a Docker image
      #   run: docker build -t your/image-to-test .

      # - name: Snyk Container monitor
      #   run: snyk container monitor your/image-to-test --file=Dockerfile

      # Carga de Resultados
      - name: Upload Snyk results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif